import random
# https://docs.python.org/3/library/random.html



rand_num = random.randint(1, 10)
print(rand_num)
# This will produce a random whole number between 1 and 10 (inclusive).
# a <= random.randint(a,b) <= b

rand_num_0_to_1 = random.random()
print(rand_num_0_to_1)
# This will produce a random floating point number between 0 and 1 (not included).
# 0.0 <= random.random() < 1.0
# You can expand the range of random numbers generated by this method using multiplication.

random_float = random.uniform(1, 10)
# This will generate a random floating point number between 1 and 10.
# a <= random.uniform(a,b) <= b

# Heads or Tails
if rand_num % 2 == 0:
    print("Heads")
else:
    print("Tail")
